исправил дублирование java + переписал protect main'a

diff --git a/.github/workflows/ci-orchestrator.yml b/.github/workflows/ci-orchestrator.yml
--- a/.github/workflows/ci-orchestrator.yml
+++ b/.github/workflows/ci-orchestrator.yml
@@ -7,6 +7,10 @@ on:
       - main
       - develop
 
+  pull_request:
+    branches:
+      - main
+
   schedule:
     - cron: '0 0 * * *'
 
@@ -51,6 +55,38 @@ jobs:
     secrets: inherit
 
 
+  ci-passed:
+
+    name: CI Tests Passed
+
+    needs:
+      - selenium
+      - docker
+
+    if: always()
+
+    runs-on: ubuntu-latest
+
+    steps:
+
+      - name: Check test results
+        run: |
+          echo "Selenium result: ${{ needs.selenium.result }}"
+          echo "Docker result: ${{ needs.docker.result }}"
+
+          if [ "${{ needs.selenium.result }}" != "success" ]; then
+            echo "Selenium CI failed."
+            exit 1
+          fi
+
+          if [ "${{ needs.docker.result }}" != "success" ]; then
+            echo "Docker CI failed."
+            exit 1
+          fi
+
+          echo "All CI tests passed."
+
+
   publish:
 
     name: Publish Allure Pages
@@ -59,7 +95,7 @@ jobs:
       - selenium
       - docker
 
-    if: always()
+    if: always() && github.event_name != 'pull_request'
 
     uses: ./.github/workflows/allure-pages.yml
 
